language: python
python:
- 2.7
install:
- pip install tox-travis
script:
- tox
notifications:
  slack:
    rooms:
      secure: IWKnnCrZSX5FLcrnUstCMVM0IHi64c8Dn+qBqCI+jRBmgaN3iI59U/Dq/1GGFVN8DLZsE0SEq0rEpMtsQ/20seYFmkkHFG9ArQmwltawRi/xqrUIDRHAMOOHV9JDXmhxQozyqu7BaBiV3RMERa8hbMFbDVu2MkzZkrx1Cchl84w1flIaHa3mnOf1FU/ujjS+G6ruuZfLhFRWKrnLyamXzwcROrhxmjCO7VEabCGnh4qcHAFqB+rJcnr1X67/h0EbFjfdhVQ+JQ6u3D7aBm21tzPE46TavRzHBuDBsjdr6FStqRdun5XduRGnK8mISTLfqIMgPflgBuDjkq+RfTU91mbcay2ESvkjRP0ZcIRh6IlANURwEAanZwr+2e4dmv+xrxOq5Rm29NjErVo4UW12ppmYX2wKewjmMj7hm9gI+BD0CjDWHNWym+dEJkW/7Ivg5C5RtxFXduOM3vkBo1xZIhTz6nCPGXwDCm3sjRY6eyoXYRUXw3RBx10uT4yVxAQaq7ZL8WxdDYJAl6SnML24FOJ9/CaQ+rJO+884OYUXxJASqsIc4Zc1GFLmI8qgPwkv1lSZnZqr86hKUwZclzvATzj9ZXvCWpVAadZBss3SX8Ji76mzgNnR+bpLpX2TEyxZqh6vlmN9u56sXai2Npkj+zuwN18daLtsC62QCfa2Tcg=
    on_success: change
    on_failure: always
