# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 08:53


from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_blogindexpage_blogpost_blogposttag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='body'),
            preserve_default=False,
        ),
    ]
