# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_blogpost_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workpage',
            old_name='categories',
            new_name='tags',
        ),
    ]
