# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 14:41


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_workcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.WorkCategory'),
        ),
    ]
