# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0037_auto_20171024_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateField(),
        ),
    ]
