# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationIdea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('affiliation', models.CharField(max_length=255)),
                ('Country', django_countries.fields.CountryField(max_length=2)),
                ('email', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, null=True)),
                ('publication_title', models.CharField(max_length=255)),
                ('scholarly_discipline', models.CharField(max_length=255)),
                ('keywords', models.CharField(max_length=255)),
                ('summary', models.TextField(max_length=10000)),
                ('link', models.URLField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationIdeaPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('thankyou_page_title', models.CharField(help_text=b"Title text to use for the 'thank you' page", max_length=255)),
                ('thankyou_page_message', models.TextField(help_text=b"Text to use for the 'thank you' page")),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
