# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 10:05


import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sup', '0002_rename_field_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationidea',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=b'sup/', validators=[django.core.validators.FileExtensionValidator([b'pdf'])]),
        ),
    ]
